AddressBookMVC/Controllers/LOC_CityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using System.Data;
using AddressBookMVC.Models;
using System;
using System.Collections.Generic;
using AddressBookMVC.DAL;

namespace AddressBookMVC.Controllers
{

    public class LOC_CityController : Controller
    {
        #region Configuration
        private IConfiguration Configuration;
        public LOC_CityController(IConfiguration _configuration)

        {
            Configuration = _configuration;
        }
        #endregion

        #region Index
        public IActionResult Index()
        {
            #region SelectAll
           
            
            string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
            LOC_DAL dalLOC = new LOC_DAL();
            DataTable dt = dalLOC.dbo_PR_LOC_City_SelectAll(connectionstr);
            return View("LOC_CityList", dt);

            /* DataTable dt = new DataTable();
             SqlConnection conn = new SqlConnection(connectionstr);

             conn.Open();

             SqlCommand objCmd = conn.CreateCommand();
             objCmd.CommandType = CommandType.StoredProcedure;
             objCmd.CommandText = "PR_LOC_City_SelectAll";
             SqlDataReader objSDR = objCmd.ExecuteReader();
             dt.Load(objSDR);

             conn.Close();*/

            #endregion
        }
        #endregion

        #region Add
        public IActionResult Add(int CityID)
        {

            #region Country Drop Down

            string connectionstr1 = this.Configuration.GetConnectionString("myConnectionStrings");
            DataTable dt1 = new DataTable();

            SqlConnection conn1 = new SqlConnection(connectionstr1);

            conn1.Open();

            SqlCommand objCmd1 = conn1.CreateCommand();
            objCmd1.CommandType = CommandType.StoredProcedure;
            objCmd1.CommandText = "PR_LOC_Country_SelectForDropDown";
            SqlDataReader objSDR1 = objCmd1.ExecuteReader();
            dt1.Load(objSDR1);
            conn1.Close();


            List<LOC_Country_SelectForDropDownModel> list = new List<LOC_Country_SelectForDropDownModel>();

            foreach (DataRow dr in dt1.Rows)
            {
                LOC_Country_SelectForDropDownModel vlst = new LOC_Country_SelectForDropDownModel();
                vlst.CountryID = Convert.ToInt32(dr["CountryID"]);
                vlst.CountryName = dr["CountryName"].ToString();
                list.Add(vlst);
            }
            ViewBag.CountryList = list;
            

            List<LOC_State_SelectForDropDownModel> list1 = new List<LOC_State_SelectForDropDownModel>();
            ViewBag.StateList = list1;



            #endregion


            #region Select By PK

            if (CityID != null)
            {
                string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
                LOC_DAL dalLOC = new LOC_DAL();

                DataTable dt = dalLOC.dbo_PR_LOC_City_SelectByPK(connectionstr, CityID);
                if (dt.Rows.Count > 0)
                {
                    LOC_CityModel model = new LOC_CityModel();
                    foreach (DataRow dr in dt.Rows)
                    {
                        DropDownByCountry(Convert.ToInt32(dr["CountryID"]));
                        model.StateID = Convert.ToInt32(dr["StateID"]);
                        model.CityID = Convert.ToInt32(dr["CityID"]);
                        model.CountryID = Convert.ToInt32(dr["CountryID"]);
                        model.CityName = dr["CityName"].ToString();
                        model.PinCode = dr["PinCode"].ToString();
                        model.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                        model.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);
                    }
                    return View("LOC_CityAddEdit", model);
                }


                /*string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
                SqlConnection conn = new SqlConnection(connectionstr);

                conn.Open();

                SqlCommand objCmd = conn.CreateCommand();
                objCmd.CommandType = CommandType.StoredProcedure;
                objCmd.CommandText = "PR_LOC_City_SelectByPK";
                objCmd.Parameters.Add("@CityID", SqlDbType.Int).Value = CityID;
                DataTable dt = new DataTable();
                SqlDataReader objSDR = objCmd.ExecuteReader();
                dt.Load(objSDR);

                LOC_CityModel  modelLOC_City = new LOC_CityModel();

                foreach (DataRow dr in dt.Rows)
                {
                    DropDownByCountry(Convert.ToInt32(dr["CountryID"]));
                    modelLOC_City.StateID = Convert.ToInt32(dr["StateID"]);
                    modelLOC_City.CityID = Convert.ToInt32(dr["CityID"]);
                    modelLOC_City.CountryID = Convert.ToInt32(dr["CountryID"]);
                    modelLOC_City.CityName = dr["CityName"].ToString();
                    modelLOC_City.PinCode = dr["PinCode"].ToString();
                    modelLOC_City.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                    modelLOC_City.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);

                    return View("LOC_CityAddEdit", modelLOC_City);
                }
                conn.Close();

                // Aya Levanu baki chhe*/
            }
            #endregion

            return View("LOC_CityAddEdit");
        }
        #endregion

        #region Save
        [HttpPost]
        public IActionResult Save(LOC_CityModel modelLOC_City)
        {

            if (ModelState.IsValid)
            {
                string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");

                LOC_DAL dalLOC = new LOC_DAL();


                if (modelLOC_City.CityID == null)
                {

                    if (Convert.ToBoolean(dalLOC.dbo_PR_LOC_City_Insert(connectionstr, modelLOC_City)))
                    {
                        TempData["CityInsertMessage"] = "Record inserted successfully";

                    }
                }
                else
                {
                    if (Convert.ToBoolean(dalLOC.dbo_PR_LOC_City_UpdateByPK(connectionstr, modelLOC_City)))
                    {

                        TempData["CityUpdateMessage"] = "Record Update Successfully";

                    }
                    return RedirectToAction("Index");
                }

            }


            return RedirectToAction("Add");
        }
        #endregion

        #region Delete
        public IActionResult Delete(int CityID)
        {
            string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
           
            LOC_DAL dalLOC = new LOC_DAL();

            if (Convert.ToBoolean(dalLOC.dbo_PR_LOC_City_DeleteByPK(connectionstr, CityID)))
            {
                return RedirectToAction("Index");
            }
            return View("Index");

            /*SqlConnection conn = new SqlConnection(connectionstr);

            conn.Open();

            SqlCommand objCmd = conn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            objCmd.CommandText = "PR_LOC_City_DeleteByPK";

            objCmd.Parameters.AddWithValue("@CityID", CityID);

            objCmd.ExecuteNonQuery();


            conn.Close();
*/

        }
        #endregion

        #region DropDownByCountry
        [HttpPost]
        public IActionResult DropDownByCountry(int CountryID)
        {
            #region State Drop Down

            string connectionstr1 = this.Configuration.GetConnectionString("myConnectionStrings");
            DataTable dt1 = new DataTable();

            SqlConnection conn1 = new SqlConnection(connectionstr1);

            conn1.Open();

            SqlCommand objCmd1 = conn1.CreateCommand();
            objCmd1.CommandType = CommandType.StoredProcedure;
            objCmd1.CommandText = "PR_LOC_State_SelectForDropDown";
            objCmd1.Parameters.AddWithValue("@CountryID", CountryID);
            SqlDataReader objSDR1 = objCmd1.ExecuteReader();
            dt1.Load(objSDR1);

            conn1.Close();

            List<LOC_State_SelectForDropDownModel> list1 = new List<LOC_State_SelectForDropDownModel>();
            foreach (DataRow dr in dt1.Rows)
            {
                LOC_State_SelectForDropDownModel vlst = new LOC_State_SelectForDropDownModel();
                vlst.StateID = Convert.ToInt32(dr["StateID"]);
                vlst.StateName = dr["StateName"].ToString();
                list1.Add(vlst);
            }
            ViewBag.StateList = list1;
            var vModel = list1;
            return Json(vModel);
            
            #endregion
        }
        #endregion

        /*public IActionResult LOC_CityList()
        {


            return View();
        }*/

    }
}

AddressBookMVC/Controllers/LOC_StateController.cs
using AddressBookMVC.DAL;
using AddressBookMVC.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace AddressBookMVC.Controllers
{
    public class LOC_StateController : Controller
    {
        #region Configuration
        private IConfiguration Configuration;
        public LOC_StateController(IConfiguration _configuration)

        {
            Configuration = _configuration;
        }
        #endregion

        #region Index
        public IActionResult Index()
        {
            string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
            LOC_DAL dalLOC = new LOC_DAL();
            DataTable dt = dalLOC.dbo_PR_LOC_State_SelectAll(connectionstr);
            return View("LOC_StateList", dt);

            /* DataTable dt = new DataTable(); 

             SqlConnection conn = new SqlConnection(connectionstr);

             conn.Open();

             SqlCommand objCmd = conn.CreateCommand();
             objCmd.CommandType = CommandType.StoredProcedure;
             objCmd.CommandText = "PR_LOC_State_SelectAll";
             SqlDataReader objSDR = objCmd.ExecuteReader();

             dt.Load(objSDR);

             conn.Close();*/

        }
        #endregion

        #region Add
        public IActionResult Add(int StateID)
        {
            #region Country Drop Down

            string connectionstr1 = this.Configuration.GetConnectionString("myConnectionStrings");
            DataTable dt1 = new DataTable();

            SqlConnection conn1 = new SqlConnection(connectionstr1);

            conn1.Open();

            SqlCommand objCmd1 = conn1.CreateCommand();
            objCmd1.CommandType = CommandType.StoredProcedure;
            objCmd1.CommandText = "PR_LOC_Country_SelectForDropDown";
            SqlDataReader objSDR1 = objCmd1.ExecuteReader();
            dt1.Load(objSDR1);

          

            List<LOC_Country_SelectForDropDownModel> list = new List<LOC_Country_SelectForDropDownModel>();
            foreach (DataRow dr in dt1.Rows)
            {
                LOC_Country_SelectForDropDownModel vlst = new LOC_Country_SelectForDropDownModel(); 
                vlst.CountryID = Convert.ToInt32(dr["CountryID"]);
                vlst.CountryName = dr["CountryName"].ToString();
                list.Add(vlst); 
            }
            ViewBag.CountryList = list;
            conn1.Close();
            #endregion

            #region Select By PK

            if (StateID != null)
            {

                string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
                LOC_DAL dalLOC = new LOC_DAL();

                DataTable dt = dalLOC.dbo_PR_LOC_State_SelectByPK(connectionstr, StateID);
                if (dt.Rows.Count > 0)
                {
                    LOC_StateModel model = new LOC_StateModel();
                    foreach (DataRow dr in dt.Rows)
                    {
                        model.CountryID = Convert.ToInt32(dr["CountryID"]);
                        model.StateID = Convert.ToInt32(dr["StateID"]);
                        model.StateName = dr["StateName"].ToString();
                        model.StateCode = dr["StateCode"].ToString();
                        model.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                        model.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);

                    }
                    return View("LOC_StateAddEdit", model);
                }

                /*string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
                SqlConnection conn = new SqlConnection(connectionstr);

                conn.Open();

                SqlCommand objCmd = conn.CreateCommand();
                objCmd.CommandType = CommandType.StoredProcedure;
                objCmd.CommandText = "PR_LOC_State_SelectByPK";
                objCmd.Parameters.Add("@StateID", SqlDbType.Int).Value = StateID;
                DataTable dt = new DataTable();
                SqlDataReader objSDR = objCmd.ExecuteReader();
                dt.Load(objSDR);


                
                LOC_StateModel modelLOC_State = new LOC_StateModel();

                foreach (DataRow dr in dt.Rows)
                {
                    modelLOC_State.CountryID = Convert.ToInt32(dr["CountryID"]);
                    modelLOC_State.StateID = Convert.ToInt32(dr["StateID"]);
                    modelLOC_State.StateName = dr["StateName"].ToString();
                    modelLOC_State.StateCode = dr["StateCode"].ToString();
                    modelLOC_State.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                    modelLOC_State.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);

                    return View("LOC_StateAddEdit", modelLOC_State);
                }
               
               
                conn.Close();*/
            }
            #endregion

            return View("LOC_StateAddEdit");
        }
        #endregion

        #region Save
        [HttpPost]
        public IActionResult Save(LOC_StateModel modelLOC_State)
        {

            #region Insert

            if (ModelState.IsValid)
            {
                string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");

                LOC_DAL dalLOC = new LOC_DAL();


                if (modelLOC_State.StateID == null)
                {

                    if (Convert.ToBoolean(dalLOC.dbo_PR_LOC_State_Insert(connectionstr, modelLOC_State)))
                    {
                        TempData["StateInsertMessage"] = "Record inserted successfully";

                    }
                }
                else
                {
                    if (Convert.ToBoolean(dalLOC.dbo_PR_LOC_State_UpdateByPK(connectionstr, modelLOC_State)))
                    {

                        TempData["StateUpdateMessage"] = "Record Update Successfully";

                    }
                    return RedirectToAction("Index");
                }
            }
            
            return RedirectToAction("Add");

            #endregion
        }
        #endregion

        #region Delete
        public IActionResult Delete(int StateID)
        {
            string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
            LOC_DAL dalLOC = new LOC_DAL();

            if (Convert.ToBoolean(dalLOC.dbo_PR_LOC_State_DeleteByPK(connectionstr,StateID)))
            {
                return RedirectToAction("Index");
            }
            return View("Index");


           /* DataTable dt = new DataTable();
            SqlConnection conn = new SqlConnection(connectionstr);

            conn.Open();

            SqlCommand objCmd = conn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            objCmd.CommandText = "PR_LOC_State_DeleteByPK";

            objCmd.Parameters.AddWithValue("@StateID", StateID);

            objCmd.ExecuteNonQuery();

            conn.Close();
*/

            
        }
        #endregion


       /* public IActionResult LOC_StateList()
        {
            return View();
        }*/
    }
}

AddressBookMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AddressBookMVC</title>
    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="~/fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
    
    @*<script src="https://kit.fontawesome.com/2c56f37d48.js" crossorigin="anonymous"></script>*@



    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>

    
    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
    <link href="~/assets/css/Button.css" rel="stylesheet">
</head>
<body>



    <!-- ======= Header/Navbar ======= -->
    <nav class="navbar navbar-default navbar-trans navbar-expand-lg fixed-top">
        <div class="container">
            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDefault" aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span></span>
                <span></span>
                <span></span>
            </button>
            <a class="navbar-brand text-brand" asp-action="Index" asp-controller="Home" ><i class="fa-solid fa-address-book"></i>&nbsp;Address<span class="color-b">Book</span></a>

            <div class="navbar-collapse collapse justify-content-center" id="navbarDefault">
                <ul class="navbar-nav">

                  
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Home">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="LOC_Country">Country</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="LOC_State">State</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="LOC_City">City</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="MST_ContactCategory">Contact Category</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="CON_Contact">Contact</a>
                    </li>
                </ul>
            </div>
            

            <div class="d-flex">
                <div class="dropdown dropdown-user" >
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <span class="username username-hide-on-mobile"> Dhruv Rathod!</span>
                    </a>
                    
                    <ul class="dropdown-menu dropdown-menu-default" style="font-size:0.9rem";>
                        <li>
                            <a href="#" style="text-align:center" >
                                &nbsp;&nbsp;&nbsp;&nbsp; <i class="fa-solid fa-user"></i>  My Profile
                                
                            </a>
                            
                        </li>
                     
                        <li>
                            <a href="page_user_login_1.html">
                                &nbsp;&nbsp;&nbsp;&nbsp;  <i class="fa-solid fa-right-from-bracket"></i> Log Out
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
           
            
            

        </div>
    </nav><!-- End Header/Navbar -->


    @*<main id="main">*@

    <div class="container" >
        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>



     <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="nav-footer">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a asp-action="Index" asp-controller="Home">Home</a>
              </li>
              <li class="list-inline-item">
                <a asp-action="Index" asp-controller="LOC_Country">Country</a>
              </li>
              <li class="list-inline-item">
                <a asp-action="Index" asp-controller="LOC_State">State</a>
              </li>
              <li class="list-inline-item">
                <a asp-action="Index" asp-controller="LOC_City">City</a>
              </li>
               <li class="list-inline-item">
                <a asp-action="Index" asp-controller="MST_ContactCategory">Contact Category</a>
              </li>
              <li class="list-inline-item">
                 <a asp-action="Index" asp-controller="CON_Contact">Contact</a>
              </li>
            </ul>
          </nav>
          <div class="socials-a">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="https://github.com/dhruvrathod29" target="_blank">
                  <i class="fa-brands fa-github"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-facebook" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-twitter" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-instagram" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                 <a href="https://www.linkedin.com/in/dhruv-rathod-0514b91bb/" target="_blank" >
                  <i class="bi bi-linkedin" aria-hidden="true"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="copyright-footer">
            <p class="copyright color-text-a">
              &copy; Copyright
              <span class="color-a">Dhruv Rathod | Asp.Net Core | Web Devloper</span> All Rights Reserved.
            </p>
          </div>
          <div class="credits">
            <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=EstateAgency
          -->
            Designed by <a href="#">Dhruv Rathod</a>
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End  Footer -->


    
   
    

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>


    <script src="~/js/site.js"></script>
    <script src="~/fortawesome/fontawesome-free/js/all.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>