AddressBookMVC/Controllers/MST_ContactCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using System.Data;
using AddressBookMVC.Models;
using System;
using AddressBookMVC.DAL;

namespace AddressBookMVC.Controllers
{
    public class MST_ContactCategoryController : Controller
    {
        #region Configuration
        private IConfiguration Configuration;
        public MST_ContactCategoryController(IConfiguration _configuration)

        {
            Configuration = _configuration;
        }
        #endregion

        #region Index
        public IActionResult Index()
        {
            #region SelectAll
            string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
            CON_DAL dalCON = new CON_DAL();
            DataTable dt = dalCON.dbo_PR_MST_ContactCategory_SelectAll(connectionstr);

            return View("MST_ContactCategoryList", dt);
            /*DataTable dt = new DataTable();
            SqlConnection conn = new SqlConnection(connectionstr);

            conn.Open();

            SqlCommand objCmd = conn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            objCmd.CommandText = "PR_MST_ContactCategory_SelectAll";
            SqlDataReader objSDR = objCmd.ExecuteReader();
            dt.Load(objSDR);

            conn.Close();

            return View("MST_ContactCategoryList", dt);
            #endregion*/
           
            #endregion
        }

        #endregion

        #region Add
        public IActionResult Add(int ContactCategoryID)
        {
            #region Select By PK
            if (ContactCategoryID != null)
            {
                string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
                CON_DAL dalCON = new CON_DAL();

                DataTable dt = dalCON.dbo_PR_MST_ContactCategory_SelectByPK(connectionstr, ContactCategoryID);
                if (dt.Rows.Count > 0)
                {
                    MST_ContactCategoryModel model = new MST_ContactCategoryModel();
                    foreach (DataRow dr in dt.Rows)
                    {
                        model.ContactCategoryID = Convert.ToInt32(dr["ContactCategoryID"]);
                        model.ContactCategoryName = dr["ContactCategoryName"].ToString();
                    
                        model.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                        model.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);

                    }
                    return View("MST_ContactCategoryAddEdit", model);


                }

                    /*string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
                    SqlConnection conn = new SqlConnection(connectionstr);

                    conn.Open();

                    SqlCommand objCmd = conn.CreateCommand();
                    objCmd.CommandType = CommandType.StoredProcedure;
                    objCmd.CommandText = "PR_MST_ContactCategory_SelectByPK";
                    objCmd.Parameters.Add("@ContactCategoryID", SqlDbType.Int).Value = ContactCategoryID;
                    DataTable dt = new DataTable();
                    SqlDataReader objSDR = objCmd.ExecuteReader();
                    dt.Load(objSDR);

                    MST_ContactCategoryModel modelMST_ContactCategory = new MST_ContactCategoryModel();

                    foreach (DataRow dr in dt.Rows)
                    {
                        modelMST_ContactCategory.ContactCategoryID = Convert.ToInt32(dr["ContactCategoryID"]);
                        modelMST_ContactCategory.ContactCategoryName = dr["ContactCategoryName"].ToString();
                        modelMST_ContactCategory.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                        modelMST_ContactCategory.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);

                        return View("MST_ContactCategoryAddEdit", modelMST_ContactCategory);
                    }
                    conn.Close();*/
            }
            #endregion

            return View("MST_ContactCategoryAddEdit");
        }
        #endregion

        #region Save
        [HttpPost]
        public IActionResult Save(MST_ContactCategoryModel modelMST_ContactCategory)
        {
            if (ModelState.IsValid)
            {
                string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");

                CON_DAL dalCON = new CON_DAL();


                if (modelMST_ContactCategory.ContactCategoryID == null)
                {

                    if (Convert.ToBoolean(dalCON.dbo_PR_MST_ContactCategory_Insert(connectionstr, modelMST_ContactCategory)))
                    {
                        TempData["ContactCategoryInsertMessage"] = "Record inserted successfully";

                    }
                }
                else
                {
                    if (Convert.ToBoolean(dalCON.dbo_PR_MST_ContactCategory_UpdateByPK(connectionstr, modelMST_ContactCategory)))
                    {

                        TempData["ContactCategoryUpdateMessage"] = "Record Update Successfully";

                    }
                    return RedirectToAction("Index");
                }

                /*  #region Insert
                  string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
                  SqlConnection conn = new SqlConnection(connectionstr);

                  conn.Open();

                  SqlCommand objCmd = conn.CreateCommand();
                  objCmd.CommandType = CommandType.StoredProcedure;

                  if (modelMST_ContactCategory.ContactCategoryID == null)
                  {
                      objCmd.CommandText = "PR_MST_ContactCategory_Insert";

                  }
                  #endregion

                  #region Update By PK
                  else
                  {
                      objCmd.CommandText = "PR_MST_ContactCategory_UpdateByPK";
                      objCmd.Parameters.Add("@ContactCategoryID", SqlDbType.Int).Value = modelMST_ContactCategory.ContactCategoryID;

                  }
                  #endregion

                  objCmd.Parameters.Add("@ContactCategoryName", SqlDbType.NVarChar).Value = modelMST_ContactCategory.ContactCategoryName;
                  objCmd.Parameters.Add("@CreationDate", SqlDbType.Date).Value = DBNull.Value;
                  objCmd.Parameters.Add("@ModificationDate", SqlDbType.Date).Value = DBNull.Value;

                  if (Convert.ToBoolean(objCmd.ExecuteNonQuery()))
                  {
                      if (modelMST_ContactCategory.ContactCategoryID == null)
                          TempData["ContactCategoryInsertMessage"] = "Record Insert Successfully";
                      else
                          TempData["ContactCategoryInsertMessage"] = "Record Update Successfully";
                  }
                  conn.Close();*/
            }

           
            return RedirectToAction("Add");
        }
        #endregion

        #region Delete
        public IActionResult Delete(int ContactCategoryID)
        {
            string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
            DataTable dt = new DataTable();
            SqlConnection conn = new SqlConnection(connectionstr);

            conn.Open();

            SqlCommand objCmd = conn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            objCmd.CommandText = "PR_MST_ContactCategory_DeleteByPK";

            objCmd.Parameters.AddWithValue("@ContactCategoryID", ContactCategoryID);

            objCmd.ExecuteNonQuery();


            conn.Close();

            return RedirectToAction("Index");
        }
        #endregion

        /*public IActionResult MST_ContactCategoryList()
        {


            return View();
        }*/
    }
}

AddressBookMVC/Views/MST_ContactCategory/MST_ContactCategoryAddEdit.cshtml
@{
    ViewData["Title"] = "ContactCategory Add/Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@model MST_ContactCategoryModel


<style>
    .btn.btn-a {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-a:hover {
            background-color: #2eca6a;
            color: #000000;
        }

    .btn.btn-b {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-b:hover {
            background-color: rgba(255,0,0, 1);
            color: #ffffff;
        }
</style>

<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">ContactCategory Add Edit</h1>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-action="Index" asp-controller="MST_ContactCategory"><i class="fa-regular fa-address-book"></i> ContactCategory List</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            ContactCategory Add Edit
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        <hr />
        <br />
        <br />
    </div>


    <div class="container">
        @if (TempData["ContactCategoryInsertMessage"] != null)
        {
            <div class="alert alert-success  alert-dismissible fade show" role="alert">
                <i class="fa-solid fa-circle-check"></i><strong> Country details! </strong><label>@TempData["ContactCategoryInsertMessage"]</label>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

            @*<label class="alert alert-success alert-dismissible fade show" role="alert"></label>*@
        }
        <br />
        <form method="post" asp-controller="MST_ContactCategory" asp-action="Save">
            @Html.HiddenFor(x=>x.ContactCategoryID)
            <div class="row">

                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    ContactCategory Name :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter Contact Category Name" asp-for="ContactCategoryName" class="form-control" />
                    <span asp-validation-for="ContactCategoryName" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                
            </div>
           
            <br />
            <div class="row">
                <div class="col-md-5">
                </div>
                <div class="col-md-1">
                    <input type="submit" value="Save" class="btn btn-a" />
                </div>
                
                <div class="col-md-1">
                    <a class="btn btn-b" asp-action="Index" asp-controller="MST_ContactCategory">
                        Cancel
                    </a>
                </div>
            </div>
        </form>

    </div>
</section><!-- End Intro Single-->

AddressBookMVC/Views/MST_ContactCategory/MST_ContactCategoryList.cshtml
@{
    Layout = "_Layout";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@using System.Data
@model DataTable



<style>
    .btn.btn-a {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-a:hover {
            background-color: #2eca6a;
            color: #000000;
        }

    .btn.btn-b {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-b:hover {
            background-color: #ff0000;
            color: #ffffff;
        }
</style>



<!-- ======= Intro Single ======= -->
<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">Contact Category List</h1>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-action="Add" asp-controller="MST_ContactCategory"><i class="fa-solid fa-square-plus"></i> Contact Category Edit </a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                           Contact Category List
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        <hr />

        <div class="row">
            <div class="col-md-9">
            </div>
            <div class="col-md-3 d-flex dataTable_filter" id="sample_1_filter">
                <input type="text" placeholder="Serach Here...!" class="form-control" id="sample_1" aria-controls="sample_1" />

                <button type="button" class="btn btn-b-n navbar-toggle-box navbar-toggle-box-collapse" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01">
                    <i class="bi bi-search"></i>

                </button>
            </div>
        </div>
    </div>
</section><!-- End Intro Single-->
@if (TempData["ContactCategoryUpdateMessage"] != null)
{
    <div class="alert alert-success  alert-dismissible fade show" role="alert">
        <i class="fa-solid fa-circle-check"></i><strong> Country details! </strong><label>@TempData["ContactCategoryUpdateMessage"]</label>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    @*<label class="alert alert-success alert-dismissible fade show" role="alert"></label>*@
}
<div style="overflow-x :auto">
    <table class="table table-hover" id="sample_1">

        <thead>
            <tr>
                <th>Contact Category ID</th>

                <th>Contact Category Name</th>
                <th>Creation Date</th>
                <th>Modification Date</th>
                <th>Action</th>
            </tr>


        </thead>
        <tbody id="sample_2">
            @foreach (DataRow dr in Model.Rows)
            {
                <tr>
                    <td>@dr["ContactCategoryID"]</td>

                    <td>@dr["ContactCategoryName"]</td>
                  
                    <td>@Convert.ToDateTime(dr["CreationDate"]).ToString("dd-MM-yyyy")</td>
                    <td>@Convert.ToDateTime(dr["ModificationDate"]).ToString("dd-MM-yyyy")</td>


                    <td class="d-flex">
                        <form method="post" asp-controller="MST_ContactCategory" asp-action="Delete">
                            <input type="hidden" name="ContactCategoryID" value="@Convert.ToInt32(dr["ContactCategoryID"].ToString())">
                            <button type="submit" class="btn btn-b" onclick="return confirm('Are you sure you want to delete : @dr["ContactCategoryName"] ')">
                                <i class="fa-solid fa-trash"></i>
                            </button>

                        </form>
                        &nbsp;

                        &nbsp;
                        &nbsp;
                        &nbsp;
                        <form method="post" asp-controller="MST_ContactCategory" asp-action="Add">
                            <input type="hidden" name="ContactCategoryID" value="@Convert.ToInt32(dr["ContactCategoryID"].ToString())">
                            <button type="submit" class="btn btn-a">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </button>
                        </form>

                    </td>

                </tr>
            }

        </tbody>
    </table>

</div>


@section Scripts{
    <script>
        $(document).ready(function () {
            $("#sample_1").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#sample_2 tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}