AddressBookMVC/Controllers/CON_ContactController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using System.Data;
using AddressBookMVC.Models;
using System;
using System.Collections.Generic;
using System.Collections;
using System.IO;
using AddressBookMVC.DAL;

namespace AddressBookMVC.Controllers
{
   
    public class CON_ContactController : Controller
    {
        #region Configuration
        private IConfiguration Configuration;
        public CON_ContactController(IConfiguration _configuration)

        {
            Configuration = _configuration;
        }
        #endregion

        #region Index
        public IActionResult Index()
        {
            #region SelectAll
            string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");

            CON_DAL dalCON = new CON_DAL();
            DataTable dt = dalCON.dbo_PR_CON_Contact_SelectAll(connectionstr);

            return View("CON_ContactList", dt);
            /*  DataTable dt = new DataTable();
              SqlConnection conn = new SqlConnection(connectionstr);

              conn.Open();

              SqlCommand objCmd = conn.CreateCommand();
              objCmd.CommandType = CommandType.StoredProcedure;
              objCmd.CommandText = "PR_CON_Contact_SelectAll";
              SqlDataReader objSDR = objCmd.ExecuteReader();
              dt.Load(objSDR);

              conn.Close();

              return View("CON_ContactList", dt);*/
            #endregion
        }
        #endregion

        #region Add
        public IActionResult Add(int ContactID)
        {

            #region Country Drop Down

            string connectionstr1 = this.Configuration.GetConnectionString("myConnectionStrings");
            DataTable dt1 = new DataTable();

            SqlConnection conn1 = new SqlConnection(connectionstr1);

            conn1.Open();

            SqlCommand objCmd1 = conn1.CreateCommand();
            objCmd1.CommandType = CommandType.StoredProcedure;
            objCmd1.CommandText = "PR_LOC_Country_SelectForDropDown";
            SqlDataReader objSDR1 = objCmd1.ExecuteReader();
            dt1.Load(objSDR1);
            conn1.Close();



            List<LOC_Country_SelectForDropDownModel> list = new List<LOC_Country_SelectForDropDownModel>();
            foreach (DataRow dr in dt1.Rows)
            {
                LOC_Country_SelectForDropDownModel vlst = new LOC_Country_SelectForDropDownModel();
                vlst.CountryID = Convert.ToInt32(dr["CountryID"]);
                vlst.CountryName = dr["CountryName"].ToString();
                list.Add(vlst);
            }
            ViewBag.CountryList = list;


            List<LOC_State_SelectForDropDownModel> list1 = new List<LOC_State_SelectForDropDownModel>();
            ViewBag.StateList = list1;
            List<LOC_City_SelectForDropDownModel> list2 = new List<LOC_City_SelectForDropDownModel>();
            ViewBag.CityList = list2;   

            #endregion

            #region Contact Category Drop Down
            string connectionstr4 = this.Configuration.GetConnectionString("myConnectionStrings");
            DataTable dt4 = new DataTable();

            SqlConnection conn4 = new SqlConnection(connectionstr4);

            conn4.Open();

            SqlCommand objCmd4 = conn4.CreateCommand();
            objCmd4.CommandType = CommandType.StoredProcedure;
            objCmd4.CommandText = "PR_MST_ContactCategory_SelectForDropDown";
            SqlDataReader objSDR4 = objCmd4.ExecuteReader();
            dt4.Load(objSDR4);



            List<MST_ContactCategory_SelectForDropDownModel> list4 = new List<MST_ContactCategory_SelectForDropDownModel>();
            foreach (DataRow dr in dt4.Rows)
            {
                MST_ContactCategory_SelectForDropDownModel vlst4 = new MST_ContactCategory_SelectForDropDownModel();
                vlst4.ContactCategoryID = Convert.ToInt32(dr["ContactCategoryID"]);
                vlst4.ContactCategoryName = dr["ContactCategoryName"].ToString();
                list4.Add(vlst4);
            }
            ViewBag.ContactCategoryList = list4;
            conn4.Close();
            #endregion

            #region Select By PK
            if (ContactID != null)
            {

                string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
                CON_DAL dalCON = new CON_DAL();

                DataTable dt = dalCON.dbo_PR_CON_Contact_SelectByPK(connectionstr, ContactID);
                if (dt.Rows.Count > 0)
                {
                    CON_ContactModel model = new CON_ContactModel();
                    foreach (DataRow dr in dt.Rows)
                    {
                        DropDownByCountry(Convert.ToInt32(dr["CountryID"]));
                        DropDownByState(Convert.ToInt32(dr["StateID"]));
                        model.ContactID = Convert.ToInt32(dr["ContactID"]);
                        model.CountryID = Convert.ToInt32(dr["CountryID"]);
                        model.StateID = Convert.ToInt32(dr["StateID"]);
                        model.CityID = Convert.ToInt32(dr["CityID"]);
                        model.ContactCategoryID = Convert.ToInt32(dr["ContactCategoryID"]);
                        model.ContactName = dr["ContactName"].ToString();
                        model.Address = dr["Address"].ToString();
                        model.PinCode = dr["PinCode"].ToString();
                        model.MobileNo = dr["MobileNo"].ToString();
                        model.AlternetContact = dr["AlternetContact"].ToString();
                        model.Email = dr["Email"].ToString();
                        model.BirthDate = Convert.ToDateTime(dr["BirthDate"]);
                        model.LinkedIn = dr["LinkedIn"].ToString();
                        model.Twitter = dr["Twitter"].ToString();
                        model.Insta = dr["Insta"].ToString();
                        model.Gender = dr["Gender"].ToString();

                        model.PhotoPath = dr["PhotoPath"].ToString();

                        model.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                        model.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);

                    }
                    return View("CON_ContactAddEdit", model);


                }


                /*string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
                SqlConnection conn = new SqlConnection(connectionstr);

                conn.Open();

                SqlCommand objCmd = conn.CreateCommand();
                objCmd.CommandType = CommandType.StoredProcedure;
                objCmd.CommandText = "PR_CON_Contact_SelectByPK";
                objCmd.Parameters.Add("@ContactID", SqlDbType.Int).Value = ContactID;
                DataTable dt = new DataTable();
                SqlDataReader objSDR = objCmd.ExecuteReader();
                dt.Load(objSDR);

                CON_ContactModel modelCON_ContactModel = new CON_ContactModel();

                foreach (DataRow dr in dt.Rows)
                {
                    DropDownByCountry(Convert.ToInt32(dr["CountryID"]));
                    DropDownByState(Convert.ToInt32(dr["StateID"]));
                    modelCON_ContactModel.ContactID = Convert.ToInt32(dr["ContactID"]);
                    modelCON_ContactModel.CountryID = Convert.ToInt32(dr["CountryID"]);
                    modelCON_ContactModel.StateID = Convert.ToInt32(dr["StateID"]);
                    modelCON_ContactModel.CityID = Convert.ToInt32(dr["CityID"]);
                    modelCON_ContactModel.ContactCategoryID = Convert.ToInt32(dr["ContactCategoryID"]);
                    modelCON_ContactModel.ContactName = dr["ContactName"].ToString();
                    modelCON_ContactModel.Address = dr["Address"].ToString();
                    modelCON_ContactModel.PinCode = dr["PinCode"].ToString();
                    modelCON_ContactModel.MobileNo = dr["MobileNo"].ToString();
                    modelCON_ContactModel.AlternetContact = dr["AlternetContact"].ToString();
                    modelCON_ContactModel.Email = dr["Email"].ToString();
                    modelCON_ContactModel.BirthDate = Convert.ToDateTime(dr["BirthDate"]);
                    modelCON_ContactModel.LinkedIn = dr["LinkedIn"].ToString();
                    modelCON_ContactModel.Twitter = dr["Twitter"].ToString();
                    modelCON_ContactModel.Insta = dr["Insta"].ToString();
                    modelCON_ContactModel.Gender = dr["Gender"].ToString();

                    modelCON_ContactModel.PhotoPath = dr["PhotoPath"].ToString();

                    modelCON_ContactModel.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                    modelCON_ContactModel.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);

                    return View("CON_ContactAddEdit", modelCON_ContactModel);
                }
                conn.Close();*/
            }
            #endregion

            return View("CON_ContactAddEdit");
        }
        #endregion

        #region Save
        [HttpPost]
        public IActionResult Save(CON_ContactModel modelCON_Contact)
        {
            #region PhotoPath
            if (modelCON_Contact.File != null)
            {
                string FilePath = "wwwroot\\Upload";
                string path = Path.Combine(Directory.GetCurrentDirectory(), FilePath);

                if (!Directory.Exists(path))
                    Directory.CreateDirectory(path);

                string fileNameWithPath = Path.Combine(path, modelCON_Contact.File.FileName);
                modelCON_Contact.PhotoPath = "~" + FilePath.Replace("wwwroot\\", "/") + "/" + modelCON_Contact.File.FileName;

                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    modelCON_Contact.File.CopyTo(stream);

AddressBookMVC/Views/CON_Contact/CON_ContactAddEdit.cshtml
@{
    ViewData["Title"] = "Contact Add/Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@model CON_ContactModel

<style>
    .btn.btn-a {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-a:hover {
            background-color: #2eca6a;
            color: #000000;
        }

    .btn.btn-b {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-b:hover {
            background-color: rgba(255,0,0, 1);
            color: #ffffff;
        }
</style>

<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">Contact Add Edit</h1>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-action="Index" asp-controller="CON_Contact"><i class="fa-regular fa-address-book"></i> Contact List</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            Contact Add Edit
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        <hr />
        <br />
        <br />
    </div>


    <div class="container">
        @if (TempData["ContactInsertMessage"] != null)
        {
            <div class="alert alert-success  alert-dismissible fade show" role="alert">
                <i class="fa-solid fa-circle-check"></i><strong> Country details! </strong><label>@TempData["ContactInsertMessage"]</label>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

            @*<label class="alert alert-success alert-dismissible fade show" role="alert"></label>*@
        }
        <br />
        <form method="post" asp-controller="CON_Contact" asp-action="Save" enctype="multipart/form-data">
            @Html.HiddenFor(x=>x.ContactID)
            @Html.HiddenFor(x=>x.PhotoPath)
            <div class="row">

                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                     Country ID :-
                </div>
                <div class="col-md-3">
                    <select asp-for="CountryID" asp-items="@(new SelectList(ViewBag.CountryList,"CountryID","CountryName"))" class="form-control" onchange="stateChange()">
                        <option value="">Select Country</option>
                    </select>
                    <span asp-validation-for="CountryID" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    State  :-
                </div>
                <div class="col-md-3">
                    <select asp-for="StateID" asp-items="@(new SelectList(ViewBag.StateList,"StateID","StateName"))" class="form-control" onchange="cityChange()">
                        <option value="">Select State</option>
                    </select>
                    <span asp-validation-for="StateID" class="text-danger"></span>
                </div>
            </div>
            <br />

            <div class="row">

                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    City ID :-
                </div>
                <div class="col-md-3">
                    <select asp-for="CityID" asp-items="@(new SelectList(ViewBag.CityList,"CityID","CityName"))" class="form-control">
                        <option value="">Select City</option>
                    </select>
                    <span asp-validation-for="CityID" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    ContactCategory ID :-
                </div>
                <div class="col-md-3">
                    <select asp-for="ContactCategoryID" asp-items="@(new SelectList(ViewBag.ContactCategoryList,"ContactCategoryID","ContactCategoryName"))" class="form-control">
                        <option value="">Select ContactCategory</option>
                    </select>
                    <span asp-validation-for="ContactCategoryID" class="text-danger"></span>
                </div>
            </div>
            <br />

            <div class="row">

                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                     Contact Name :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter Contact Name" asp-for="ContactName" class="form-control" />
                    <span asp-validation-for="ContactName" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    Address :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter Address" asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
            <br />


            <div class="row">

                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    Pin Code :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter PinCode" asp-for="PinCode" class="form-control" />
                    <span asp-validation-for="PinCode" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                     Mobile No :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter Mobile No" asp-for="MobileNo" class="form-control" />
                    <span asp-validation-for="MobileNo" class="text-danger"></span>
                </div>
            </div>

            <br />


            <div class="row">

                <div class="col-md-2">
                    Alternet Contact :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter Alternet Contact" asp-for="AlternetContact" class="form-control" />
                    <span asp-validation-for="AlternetContact" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    Email :-
                </div>
                <div class="col-md-3">
                    <input type="email" placeholder="Enter Email" asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <br />
            <div class="row">

                <div class="col-md-2">
                    Birth Date :-
                </div>
                <div class="col-md-3">
                    <input type="date" placeholder="Enter Birth Date" asp-for="BirthDate" class="form-control" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    LinkedIn :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter LinkedIn Id" asp-for="LinkedIn" class="form-control" />
                    <span asp-validation-for="LinkedIn" class="text-danger"></span>
                </div>
            </div>
            <br />
            <div class="row">

                <div class="col-md-2">
                         Twitter :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter Twitter Id" asp-for="Twitter" class="form-control" />
                    <span asp-validation-for="Twitter" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    Insta :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter Instagram Id" asp-for="Insta" class="form-control" />
                    <span asp-validation-for="Insta" class="text-danger"></span>
                </div>
            </div>
            <br />
            <div class="row">

                <div class="col-md-2">
                    Gender :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter Gender" asp-for="Gender" class="form-control" />
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                   
                    Photo Upload  :-

                </div>
                <div class="col-md-3">

                    <input type="file" placeholder="Upload Photo" asp-for="File" class="form-control" />
                    <span asp-validation-for="PhotoPath" class="text-danger"></span>

                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-5">
                </div>
                <div class="col-md-1">
                    <input type="submit" value="Save" class="btn btn-a" />
                </div>
                
                <div class="col-md-1">
                    <a class="btn btn-b" asp-action="Index" asp-controller="CON_Contact">
                        Cancel
                    </a>
                </div>
            </div>
        </form>

    </div>
</section><!-- End Intro Single-->
@section Scripts{
    <script>

        //State Ajax
        function stateChange() {
            var CountryID = $("#CountryID").val();
            if (CountryID !== "") {
                $("#StateID").empty();
                $("#StateID").append($("<option></option>").val("").html("Select State"));
                $.ajax({
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    contentType: "application/json; charset=utf-8",
                    url: "@Url.Action("DropDownByCountry","LOC_City")" + "?CountryID=" + CountryID,
                    dataType: "json",
                    success: function (Result) {
                        console.log(Result);
                        $.each(Result,
                            function (key, value) {
                                $("#StateID").append($("<option></option>").val(value.stateID).html(value.stateName));
                            });
                    },
                    error: function (r) {
                        alert("Error while loading DropDown");
                    }

                });
            }
            else {
                $("#StateID").empty();
                $("#StateID").append($("<option></option>").val("").html("Select State"));
            }
        }


        $(window).on('load', function () {
            console.log('All assets are loaded')
        })
        function abc() {
            alert("Error while change");
        }

        //City Ajax

        function cityChange() {
            var StateID = $("#StateID").val();
            if (StateID !== "") {
                $("#CityID").empty();
                $("#CityID").append($("<option></option>").val("").html("Select City"));
                $.ajax(
                    {
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        url: "@Url.Action("DropDownByState","CON_Contact")" + "?&StateID=" + StateID,
                        data: {},
                        dataType: "json",
                        success: function (Result) {
                            $.each(Result,
                                function (key, value) {
                                    $("#CityID").append($("<option></option>").val(value.cityID).html(value.cityName));
                                });
                        },
                        error: function (r) {
                            alert("Error while loading combobox.");
                        }
                    });
            } else {
                $("#CityID").empty();
                $("#CityID").append($("<option></option>").val("").html("Select City"));
            }
        }


    </script>
}

AddressBookMVC/Views/CON_Contact/CON_ContactList.cshtml
@{
    Layout = "_Layout";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

@using System.Data
@model  DataTable



<style>
    .btn.btn-a {
      text-decoration: none;
      background-color: #000000;
      color: #ffffff;
    }
    .btn.btn-a:hover {
      background-color: #2eca6a;
      color: #000000;
    }
    .btn.btn-b {
      text-decoration: none;
      background-color: #000000;
      color: #ffffff;
    }
    .btn.btn-b:hover {
      background-color: #ff0000;
      color: #ffffff;
    }
</style>



<!-- ======= Intro Single ======= -->
<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">Contact List</h1>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-action="Add" asp-controller="CON_Contact"><i class="fa-solid fa-square-plus"></i> Contact Add Edit </a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                           Contact List
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-9">
            </div>
            <div class="col-md-3 d-flex dataTable_filter" id="sample_1_filter">
                <input type="text" placeholder="Serach Here...!" class="form-control" id="sample_1" aria-controls="sample_1" />

                <button type="button" class="btn btn-b-n navbar-toggle-box navbar-toggle-box-collapse" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01">
                    <i class="bi bi-search"></i>

                </button>
            </div>
        </div>
    </div>
</section><!-- End Intro Single-->
@if (TempData["ContactUpdateMessage"] != null)
{
    <div class="alert alert-success  alert-dismissible fade show" role="alert">
        <i class="fa-solid fa-circle-check"></i><strong> Country details! </strong><label>@TempData["ContactUpdateMessage"]</label>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    @*<label class="alert alert-success alert-dismissible fade show" role="alert"></label>*@
}
<div style="overflow-x :auto">
    <table class="table table-hover" id="sample_1">

        <thead>
            <tr>
                <th>Action</th>
                <th>Photo</th>

                <th>Contact ID</th>
                <th>Country Name</th>
                <th>State Name</th>
                <th>City Name</th>
                <th>Contact Category Name</th>
                <th>Contact Name</th>
                <th>Address</th>
                <th>PinCode</th>
                <th>Mobile No</th>
                <th>Alternet Contact</th>
                <th>Email</th>
                <th>BithDate</th>
                <th>LinkedIn</th>
                <th>Twitter</th>
                <th>Insta</th>
                <th>Gender</th>
                <th>Creation Date</th>
                <th>Modification Date</th>
            </tr>


        </thead>
        <tbody id="sample_2">
            @foreach (DataRow dr in Model.Rows)
            {
                <tr>
                    <td class="d-flex">
                        <form method="post" asp-controller="CON_Contact" asp-action="Delete">
                            <input type="hidden" name="ContactID" value="@Convert.ToInt32(dr["ContactID"].ToString())">
                            <button type="submit" class="btn btn-b" onclick="return confirm('Are you sure you want to delete : @dr["ContactName"] ')">
                                <i class="fa-solid fa-trash"></i>
                            </button>



                        </form>
                        &nbsp;

                        &nbsp;
                        &nbsp;
                        &nbsp;
                        <form method="post" asp-controller="CON_Contact" asp-action="Add">
                            <input type="hidden" name="ContactID" value="@Convert.ToInt32(dr["ContactID"].ToString())">
                            <button type="submit" class="btn btn-a">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </button>
                        </form>

                    </td>
                    
                    <td><img src="@Url.Content(dr["PhotoPath"].ToString())" alt="@dr["CountryName"]" style="height:50px; width:50px"></td>
                    <td>@dr["ContactID"]</td>
                    <td>@dr["CountryName"]</td>
                    <td>@dr["StateName"]</td>
                    <td>@dr["CityName"]</td>
                    <td>@dr["ContactCategoryName"]</td>

                    <td>@dr["ContactName"]</td>
                    <td>@dr["Address"]</td>
                    <td>@dr["PinCode"]</td>
                    <td>@dr["MobileNo"]</td>
                    <td>@dr["AlternetContact"]</td>
                    <td>@dr["Email"]</td>
                    <td>@Convert.ToDateTime(dr["BirthDate"]).ToString()</td>
                    <td>@dr["LinkedIn"]</td>
                    <td>@dr["Twitter"]</td>
                    <td>@dr["Insta"]</td>
                    <td>@dr["Gender"]</td>
                    <td>@Convert.ToDateTime(dr["CreationDate"]).ToString("dd-MM-yyyy")</td>
                    <td>@Convert.ToDateTime(dr["ModificationDate"]).ToString("dd-MM-yyyy")</td>


                  

                </tr>
            }

        </tbody>
    </table>

</div>


@section Scripts{
    <script>
        $(document).ready(function () {
            $("#sample_1").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#sample_2 tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}