AddressBookMVC/Controllers/LOC_CountryController.cs
using AddressBookMVC.DAL;
using AddressBookMVC.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Data;
using System.Data.SqlClient;

namespace AddressBookMVC.Controllers
{
    public class LOC_CountryController : Controller
    {
        #region Configuration

        private IConfiguration Configuration;
        public LOC_CountryController(IConfiguration _configuration)
        
        {
            Configuration = _configuration;
        }
        #endregion

        #region Index

        #region Select All
        public IActionResult Index()
        {
            string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
            LOC_DAL dalLOC = new LOC_DAL();
            DataTable dt = dalLOC.dbo_PR_LOC_Country_SelectAll(connectionstr);

            return View("LOC_CountryList", dt);

            /*  DataTable dt = new DataTable();
              SqlConnection conn = new SqlConnection(connectionstr);

              conn.Open();

              SqlCommand objCmd = conn.CreateCommand();
              objCmd.CommandType = CommandType.StoredProcedure;
              objCmd.CommandText = "PR_LOC_Country_SelectAll";
              SqlDataReader objSDR = objCmd.ExecuteReader();
              dt.Load(objSDR);

              conn.Close();*/

        }
        #endregion

        #endregion

        #region Add
        public IActionResult Add(int CountryID)
        {
            #region Select By PK
            if (CountryID != null)
            {
                string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
                LOC_DAL dalLOC = new LOC_DAL();

                DataTable dt = dalLOC.dbo_PR_LOC_Country_SelectByPK(connectionstr,CountryID);
                if (dt.Rows.Count > 0)
                {
                    LOC_CountryModel model = new LOC_CountryModel();
                    foreach (DataRow dr in dt.Rows)
                    {
                        model.CountryID = Convert.ToInt32(dr["CountryID"]);
                        model.CountryName= dr["CountryName"].ToString();
                        model.CountryCode = dr["CountryCode"].ToString();
                        model.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                        model.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);

                    }
                    return View("LOC_CountryAddEdit",model);
                }



                /*  string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");
                  SqlConnection conn = new SqlConnection(connectionstr);

                  conn.Open();

                  SqlCommand objCmd = conn.CreateCommand();
                  objCmd.CommandType = CommandType.StoredProcedure;
                  objCmd.CommandText = "PR_LOC_Country_SelectByPK";
                  objCmd.Parameters.Add("@CountryID", SqlDbType.Int).Value = CountryID;
                  DataTable dt= new DataTable();
                  SqlDataReader objSDR = objCmd.ExecuteReader();
                  dt.Load(objSDR);

                  LOC_CountryModel modelLOC_CountryModel = new LOC_CountryModel();

                  foreach (DataRow dr in dt.Rows)
                  {
                      modelLOC_CountryModel.CountryID = Convert.ToInt32(dr["CountryID"]); 
                      modelLOC_CountryModel.CountryName = dr["CountryName"].ToString(); 
                      modelLOC_CountryModel.CountryCode = dr["CountryCode"].ToString(); 
                      modelLOC_CountryModel.CreationDate = Convert.ToDateTime(dr["CreationDate"]); 
                      modelLOC_CountryModel.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);

                      return View("LOC_CountryAddEdit", modelLOC_CountryModel);
                  }
                  conn.Close();*/
            }
            #endregion

            return View("LOC_CountryAddEdit");  
        }
        #endregion

        #region Save 
        [HttpPost]
        public IActionResult Save(LOC_CountryModel modelLOC_Country)
        {
            if (ModelState.IsValid)
            {
                string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");

                LOC_DAL dalLOC = new LOC_DAL();


                if (modelLOC_Country.CountryID == null)
                {

                    if (Convert.ToBoolean(dalLOC.dbo_PR_LOC_Country_Insert(connectionstr, modelLOC_Country)))
                    {
                        TempData["CountryInsertMessage"] = "Record inserted successfully";

                    }
                }
                else
                {
                    if (Convert.ToBoolean(dalLOC.dbo_PR_LOC_Country_UpdateByPK(connectionstr, modelLOC_Country)))
                    {

                        TempData["CountryUpdateMessage"] = "Record Update Successfully";

                    }
                    return RedirectToAction("Index");
                }

            }
           
            return RedirectToAction("Add");
        }
        #endregion

        #region Delete
        public IActionResult Delete(int CountryID)
        {
            string connectionstr = this.Configuration.GetConnectionString("myConnectionStrings");

            LOC_DAL dalLOC = new LOC_DAL();

            if (Convert.ToBoolean(dalLOC.dbo_PR_LOC_Country_DeleteByPK(connectionstr, CountryID)))
            {
                return RedirectToAction("Index");
            }
            return View("Index");


            /*DataTable dt = new DataTable();
            SqlConnection conn = new SqlConnection(connectionstr);

            conn.Open();

            SqlCommand objCmd = conn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            objCmd.CommandText = "PR_LOC_Country_DeleteByPK";
           
            objCmd.Parameters.AddWithValue("@CountryID", CountryID);

            objCmd.ExecuteNonQuery();

            
            conn.Close();*/

            
        }
        #endregion

       /* public IActionResult LOC_CountryList()
        {


            return View();
        }*/

    }
}

AddressBookMVC/Views/LOC_Country/LOC_CountryAddEdit.cshtml
@{
    ViewData["Title"] = "Country Add/Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@model LOC_CountryModel

<style>
    .btn.btn-a {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-a:hover {
            background-color: #2eca6a;
            color: #000000;
        }

    .btn.btn-b {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-b:hover {
            background-color: rgba(255,0,0, 1);
            color: #ffffff;
        }
</style>


<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">Country Add Edit</h1>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-action="Index" asp-controller="LOC_Country"><i class="fa-regular fa-address-book"></i> Country List</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            Country Add Edit
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        <hr />
        <br />
        <br />
    </div>


    <div class="container">

        @if (TempData["CountryInsertMessage"] != null)
        {
            <div class="alert alert-success  alert-dismissible fade show" role="alert">
                <i class="fa-solid fa-circle-check"></i><strong> Country details! </strong><label>@TempData["CountryInsertMessage"]</label>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

            @*<label class="alert alert-success alert-dismissible fade show" role="alert"></label>*@
        }
        <br />
        <form method="post" asp-controller="LOC_Country" asp-action="Save">
            @Html.HiddenFor(x=>x.CountryID)
            <div class="row">
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    Country Name :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter Country Name" required asp-for="CountryName" class="form-control" />
                    <span asp-validation-for="CountryName" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    Country Code :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter Country Code" required asp-for="CountryCode" class="form-control" />
                    <span asp-validation-for="CountryCode" class="text-danger"></span>
                </div>
            </div>
            <br />

         @*   <div class="row">
                <div class="col-md-2">

                    Creation Date :-
                </div>
                <div class="col-md-3">
                    <input type="date" placeholder="Enter Creation Date" asp-for="CreationDate" class="form-control" />
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">

                    Modification Date :-
                </div>
                <div class="col-md-3">
                    <input type="date" placeholder="Enter Modification Date" asp-for="ModificationDate" class="form-control" />
                </div>
            </div>*@
            <br />
            <div class="row">
                <div class="col-md-5">
                </div>
                <div class="col-md-1">
                    <input type="submit" value="Save" class="btn btn-a" />
                </div>

                <div class="col-md-1">

                    <a class="btn btn-b" type="submit" value="Cancel" asp-controller="LOC_Country" asp-action="Index">
                        Cancel
                    </a>

                </div>
            </div>
        </form>

    </div>
</section><!-- End Intro Single-->

AddressBookMVC/Views/LOC_Country/LOC_CountryList.cshtml
@{
    Layout = "_Layout";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@using System.Data
@model  DataTable






<style>
    .btn.btn-a {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-a:hover {
            background-color: #2eca6a;
            color: #000000;
        }

    .btn.btn-b {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-b:hover {
            background-color: #ff0000;
            color: #ffffff;
        }
</style>
<!-- ======= Intro Single ======= -->

<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">Country List</h1>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-action="Add" asp-controller="LOC_Country"><i class="fa-solid fa-square-plus"></i> Country Add Edit </a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            Country List
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        
        <hr />

        <div class="row">
            <div class="col-md-9">
                   
            </div>
            <div class="col-md-3 d-flex dataTable_filter" id="sample_1_filter">
                <input type="text" placeholder="Serach Here...!" class="form-control" id="sample_1" aria-controls="sample_1" />

                <button type="button" class="btn btn-b-n navbar-toggle-box navbar-toggle-box-collapse" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01">
                    <i class="bi bi-search"></i>

                </button>
            </div>
        </div>
        

    </div>
</section><!-- End Intro Single-->
@if (TempData["CountryUpdateMessage"] != null)
{
    <div class="alert alert-success  alert-dismissible fade show" role="alert">
        <i class="fa-solid fa-circle-check"></i><strong> Country details! </strong><label>@TempData["CountryUpdateMessage"]</label>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    @*<label class="alert alert-success alert-dismissible fade show" role="alert"></label>*@
}
<table class="table table-hover" id="sample_1">

    <thead>
        <tr>
      
            <th>Country Name</th>
            <th>Country Code</th>
            <th>Creation Date</th>
            <th>Modification Date</th>
            <th>Action</th>
           
        </tr>
        
    </thead>
    <tbody id="sample_2">
        @foreach(DataRow dr in Model.Rows) 
        {
            <tr>
                
                <td>@dr["CountryName"]</td>
                <td>@dr["CountryCode"]</td>
                <td>@Convert.ToDateTime(dr["CreationDate"]).ToString("dd-MM-yyyy")</td>
                <td>@Convert.ToDateTime(dr["ModificationDate"]).ToString("dd-MM-yyyy")</td>

                <td class="d-flex">
                  
                        <form method="post" asp-controller="LOC_Country" asp-action="Delete">
                        <input type="hidden" name="CountryID" value="@Convert.ToInt32(dr["CountryID"].ToString())" >
                        <button type="submit" class="btn btn-b" onclick="return confirm('Are you sure you want to delete : @dr["CountryName"] ')">
                            <i class="fa-solid fa-trash"></i>
                        </button>
                        </form>
                        &nbsp;
                        
                        &nbsp;
                        &nbsp;
                        &nbsp;

                         <form method="post" asp-controller="LOC_Country" asp-action="Add" asp-route-CountryID="@Convert.ToInt32(dr["CountryID"])">
                             <input type="hidden" name="CountryID" value="@Convert.ToInt32(dr["CountryID"].ToString())">
                             <button type="submit" class="btn btn-a">
                            <i class="fa-solid fa-pen-to-square"></i>
                             </button>
                         </form>
                        
                </td>
            </tr>
        }
        
    </tbody>
</table> 

@section Scripts{
    <script>
        $(document).ready(function () {
            $("#sample_1").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#sample_2 tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });

    </script>
   

}